site_name: Portfolio
site_author: Jakub Najder
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: PhatPhatPhitcht/Portfolio
repo_url: https://github.com/PhatPhatPhitcht/Portfolio

theme:
  name: material

nav:
- Strona Domowa: index.md
- Projekty:
  - "Iris": iris/index.md